many updates

diff --git a/get_network_if_data b/get_network_if_data
--- a/get_network_if_data
+++ b/get_network_if_data
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-PWD_DIR=`dirname $0`
+PWD_DIR=$(dirname $0)
+
+LOCK=/tmp/get_if_data
+
+[[ -e "${LOCK}" ]] && { echo "get_network_if_data in progress"; exit; }
+touch "${LOCK}"
 
 ISSMON_DIR="/home/monalisa/issmon/"
 OUTPUT_DIR="/home/monalisa/issmon_data/network"
@@ -9,39 +14,46 @@ TABLE="snmptable "
 GET="snmpget "
 WALK="snmpwalk "
 
+ifTable_OID=" 1.3.6.1.2.1.2.2"
+NAME_OID=" .1.3.6.1.2.1.1.5.0"
+
 SNMP_COMMUNITY=" -c iss-ro -v 2c -Pu "
-ARG2=" -CB -Cf \" ; \" IF-MIB::ifTable "
+ARG2=" -CB -Cf \" ; \" "
 ARG3=" -Oq -Ov "
-OUTPUT="/tmp/snmp_temp_network.txt"
+OUTPUT_base="/tmp/snmp_temp_network"
 
-NAME=" .1.3.6.1.2.1.1.5.0"
+get_snmp_info () {
+  local switch
+  switch="${1}"
 
-for switch in $(cat $ISSMON_DIR/list_switch) ; do
+  local GET_NAME_SWITCH="${GET} ${ARG3} ${SNMP_COMMUNITY} ${switch} ${NAME_OID} | sed 's/^\ //;s/\ /_/g'"
+  local GET_TABLE_SWITCH="${TABLE} ${SNMP_COMMUNITY} ${switch} ${ARG2} ${ifTable_OID}"
 
-  GET_NAME_SWITCH="$GET$ARG3$SNMP_COMMUNITY$switch$NAME | sed 's/^\ //;s/\ /_/g'"
-  GET_TABLE_SWITCH="$TABLE$SNMP_COMMUNITY$switch$ARG2"
+  local NAME_SWITCH=$(eval ${GET_NAME_SWITCH})
+  [[ -z "${NAME_SWITCH}" ]] && return 1;
 
-  #echo 
-  #echo $GET_NAME_SWITCH
-  #echo $GET_TABLE_SWITCH
-
-  NAME_SWITCH=`eval ${GET_NAME_SWITCH}`
-  eval ${GET_TABLE_SWITCH} > $OUTPUT
+  local OUTPUT="${OUTPUT_base}_${NAME_SWITCH}.txt"
+  eval ${GET_TABLE_SWITCH} > ${OUTPUT}
 
   #echo "Name : " $NAME_SWITCH
 
-  FILE="$OUTPUT_DIR/$NAME_SWITCH.iftbl"
-
+  local FILE_TMP="${OUTPUT_DIR}/${NAME_SWITCH}_tmp.iftbl"
+  local FILE="${OUTPUT_DIR}/${NAME_SWITCH}.iftbl"
   ##cp $OUTPUT ${FILE}.rawout
 
-  echo -e "Descr\t AdminStatus\t OperStatus\t InDiscards\t InErrors\t OutDiscards\t OutErrors"  > ${FILE}
+  echo -e "Descr\t AdminStatus\t OperStatus\t InDiscards\t InErrors\t OutDiscards\t OutErrors\t InOctets\t OutOctets"  > ${FILE_TMP}
+  awk -F" ; " '{ if ( ($3 == "ethernetCsmacd") || ($3 == "gigabitEthernet") ) { print $2,"\t",$7,"\t",$8,"\t",$13,"\t",$14,"\t",$19,"\t",$20,"\t",$10,"\t",$16; } }' ${OUTPUT} >> ${FILE_TMP}
 
-  cat $OUTPUT | awk -F" ; " '{ if ( ($3 == "ethernetCsmacd") || ($3 == "gigabitEthernet") ) { print $2,"\t",$7,"\t",$8,"\t",$13,"\t",$14,"\t",$19,"\t",$20; } }' >> ${FILE}
-  column -t ${FILE} > tmp && mv tmp -f ${FILE}
+  cat ${FILE_TMP} | column -t > ${FILE}
 
+  # after taking all data delete temp file
+  rm -rf ${OUTPUT} ${FILE_TMP}
+}
+
+for sw in $(cat ${ISSMON_DIR}/list_switch) ; do
+  get_snmp_info ${sw} &
 done
+wait
 
-# after taking all data delete temp file
-rm -rf $OUTPUT
-
+[[ -e "${LOCK}" ]] && rm -rf "${LOCK}"
 
